#!/usr/bin/env python3
"""Writes wireplay.glyph.svg, a custom SF Symbol of WirePlay's icon (monitor + HDMI plug).
Same geometry as Glyph.draw in Sources/main.swift (unit square, y up), traced as filled
outlines because symbols can't use strokes. Run it again if the icon changes."""
import math, os

S, BASE = 136.0, 31.0                     # glyph size in symbol units; centred on the cap height like Apple's tile symbols
def X(x): return x * S
def Y(y): return BASE - y * S

class Path:
    def __init__(self): self.d = []
    def M(self, x, y): self.d.append(f"M{X(x):.2f} {Y(y):.2f}"); return self
    def L(self, x, y): self.d.append(f"L{X(x):.2f} {Y(y):.2f}"); return self
    def arc(self, cx, cy, r, a, b):       # quarter arc, degrees, as one cubic
        a, b = math.radians(a), math.radians(b)
        s = 1 if b > a else -1
        k = 0.5523 * r
        p0 = (cx + r*math.cos(a), cy + r*math.sin(a)); p3 = (cx + r*math.cos(b), cy + r*math.sin(b))
        c1 = (p0[0] - s*k*math.sin(a), p0[1] + s*k*math.cos(a))
        c2 = (p3[0] + s*k*math.sin(b), p3[1] - s*k*math.cos(b))
        self.d.append("C" + " ".join(f"{X(px):.2f} {Y(py):.2f}" for px, py in (c1, c2, p3))); return self
    def Z(self): self.d.append("Z"); return self

def round_rect(p, x0, y0, x1, y1, r, reverse=False):
    if not reverse:
        p.M(x0 + r, y0).L(x1 - r, y0).arc(x1 - r, y0 + r, r, -90, 0).L(x1, y1 - r).arc(x1 - r, y1 - r, r, 0, 90)
        p.L(x0 + r, y1).arc(x0 + r, y1 - r, r, 90, 180).L(x0, y0 + r).arc(x0 + r, y0 + r, r, 180, 270).Z()
    else:
        p.M(x0 + r, y0).arc(x0 + r, y0 + r, r, 270, 180).L(x0, y1 - r).arc(x0 + r, y1 - r, r, 180, 90)
        p.L(x1 - r, y1).arc(x1 - r, y1 - r, r, 90, 0).L(x1, y0 + r).arc(x1 - r, y0 + r, r, 0, -90).Z()

p = Path()
# Monitor frame (outer 0.04–0.96 × 0.34–0.94, r 0.12; inner 0.12–0.88 × 0.42–0.86, r 0.04), gap 0.27–0.73 at the bottom.
p.M(0.27, 0.34).L(0.16, 0.34).arc(0.16, 0.46, 0.12, -90, -180).L(0.04, 0.82).arc(0.16, 0.82, 0.12, 180, 90)
p.L(0.84, 0.94).arc(0.84, 0.82, 0.12, 90, 0).L(0.96, 0.46).arc(0.84, 0.46, 0.12, 0, -90).L(0.73, 0.34)
p.L(0.73, 0.42).L(0.84, 0.42).arc(0.84, 0.46, 0.04, -90, 0).L(0.88, 0.82).arc(0.84, 0.82, 0.04, 0, 90)
p.L(0.16, 0.86).arc(0.16, 0.82, 0.04, 90, 180).L(0.12, 0.46).arc(0.16, 0.46, 0.04, 180, 270).L(0.27, 0.42).Z()
# HDMI plug head (chamfered), with the contact slot as a hole (opposite winding).
p.M(0.30, 0.58).L(0.70, 0.58).L(0.70, 0.47).L(0.62, 0.38).L(0.38, 0.38).L(0.30, 0.47).Z()
round_rect(p, 0.36, 0.475, 0.64, 0.525, 0.02)
# Boot and cable.
round_rect(p, 0.37, 0.15, 0.63, 0.345, 0.03, reverse=True)
p.M(0.455, 0.16).L(0.545, 0.16).L(0.545, 0.0).L(0.455, 0.0).Z()
# Solid parts all wind clockwise (y up); the slot winds the other way, so it's a hole.
d = " ".join(p.d)

left, right = 1391.30, 1391.30 + S
svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by Controls/make-symbol.py -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3300" height="2200">
 <g id="Notes">
  <text id="template-version" x="0" y="0" style="font-size:13">Template v.5.0</text>
 </g>
 <g id="Guides">
  <line id="Baseline-S" x1="263" x2="3036" y1="696" y2="696" stroke="#27AAE1"/>
  <line id="Capline-S" x1="263" x2="3036" y1="625.541" y2="625.541" stroke="#27AAE1"/>
  <line id="Baseline-M" x1="263" x2="3036" y1="1126" y2="1126" stroke="#27AAE1"/>
  <line id="Capline-M" x1="263" x2="3036" y1="1055.54" y2="1055.54" stroke="#27AAE1"/>
  <line id="Baseline-L" x1="263" x2="3036" y1="1556" y2="1556" stroke="#27AAE1"/>
  <line id="Capline-L" x1="263" x2="3036" y1="1485.54" y2="1485.54" stroke="#27AAE1"/>
  <line id="left-margin-Regular-M" x1="{left}" x2="{left}" y1="1030.79" y2="1150.12" stroke="#00AEEF"/>
  <line id="right-margin-Regular-M" x1="{right}" x2="{right}" y1="1030.79" y2="1150.12" stroke="#00AEEF"/>
 </g>
 <g id="Symbols">
  <g id="Regular-M" transform="matrix(1 0 0 1 {left} 1126)">
   <path d="{d}"/>
  </g>
 </g>
</svg>
'''
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Assets.xcassets/wireplay.glyph.symbolset/wireplay.glyph.svg")
open(out, "w").write(svg)
print("wrote", out)
